# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'camera_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_camera_widget(object):
    def setupUi(self, camera_widget):
        camera_widget.setObjectName("camera_widget")
        camera_widget.resize(400, 300)

        self.retranslateUi(camera_widget)
        QtCore.QMetaObject.connectSlotsByName(camera_widget)
        
        self.camera = QtWidgets.QLabel(camera_widget)
        self.camera.setGeometry(QtCore.QRect(0, 0, 640, 480))  # 카메라 화면 크기
        self.camera.setObjectName("camera")

    def retranslateUi(self, camera_widget):
        _translate = QtCore.QCoreApplication.translate
        camera_widget.setWindowTitle(_translate("camera_widget", "Camera"))
        
