# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'control_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(840, 540)
        MainWindow.setStyleSheet("QWidget {\n"
"    background-color: #2b2b2b;\n"
"    color: #f0f0f0;\n"
"    font-family: \"Segoe UI\";\n"
"    font-size: 11pt;\n"
"}\n"
"\n"
"QComboBox {\n"
"    background-color: #3c3f41;\n"
"}\n"
"\n"
"QLineEdit, QTextEdit {\n"
"    background-color: #3c3f41;\n"
"    border: 1px solid #5c5c5c;\n"
"    padding: 4px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #4a90e2;\n"
"    border: none;\n"
"    color: white;\n"
"    padding: 5px 10px;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #357ABD;\n"
"}\n"
"\n"
"QGroupBox {\n"
"    border: 1px solid #5c5c5c;\n"
"    margin-top: 10px;\n"
"}\n"
"\n"
"QGroupBox:title {\n"
"    subcontrol-origin: margin;\n"
"    left: 10px;\n"
"    padding: 0 3px 0 3px;\n"
"}\n"
"\n"
"QMenuBar {\n"
"    background-color: #1e1e1e;\n"
"    color: #ffffff;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.left_side = QtWidgets.QFrame(self.centralwidget)
        self.left_side.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.left_side.setFrameShadow(QtWidgets.QFrame.Raised)
        self.left_side.setObjectName("left_side")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.left_side)
        self.verticalLayout.setObjectName("verticalLayout")
        self.sensor_group = QtWidgets.QGroupBox(self.left_side)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.sensor_group.setFont(font)
        self.sensor_group.setObjectName("sensor_group")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.sensor_group)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.chart_1 = QtWidgets.QWidget(self.sensor_group)
        self.chart_1.setObjectName("chart_1")
        self.horizontalLayout_2.addWidget(self.chart_1)
        self.chart_2 = QtWidgets.QWidget(self.sensor_group)
        self.chart_2.setObjectName("chart_2")
        self.horizontalLayout_2.addWidget(self.chart_2)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 1)
        self.verticalLayout.addWidget(self.sensor_group)
        self.command_group = QtWidgets.QGroupBox(self.left_side)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.command_group.setFont(font)
        self.command_group.setObjectName("command_group")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.command_group)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.cmd_log = QtWidgets.QTextEdit(self.command_group)
        self.cmd_log.setObjectName("cmd_log")
        self.verticalLayout_2.addWidget(self.cmd_log)
        self.cmd_line = QtWidgets.QLineEdit(self.command_group)
        self.cmd_line.setObjectName("cmd_line")
        self.verticalLayout_2.addWidget(self.cmd_line)
        self.verticalLayout.addWidget(self.command_group)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 1)
        self.horizontalLayout.addWidget(self.left_side)
        self.right_side = QtWidgets.QFrame(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.right_side.setFont(font)
        self.right_side.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.right_side.setFrameShadow(QtWidgets.QFrame.Raised)
        self.right_side.setObjectName("right_side")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.right_side)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.box_select = QtWidgets.QComboBox(self.right_side)
        self.box_select.setObjectName("box_select")
        self.verticalLayout_3.addWidget(self.box_select)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.temp_edit = QtWidgets.QHBoxLayout()
        self.temp_edit.setObjectName("temp_edit")
        self.line_temp = QtWidgets.QLineEdit(self.right_side)
        self.line_temp.setObjectName("line_temp")
        self.temp_edit.addWidget(self.line_temp)
        self.btn_temp = QtWidgets.QPushButton(self.right_side)
        self.btn_temp.setObjectName("btn_temp")
        self.temp_edit.addWidget(self.btn_temp)
        self.temp_edit.setStretch(0, 3)
        self.temp_edit.setStretch(1, 1)
        self.verticalLayout_3.addLayout(self.temp_edit)
        self.humi_edit = QtWidgets.QHBoxLayout()
        self.humi_edit.setObjectName("humi_edit")
        self.line_humi = QtWidgets.QLineEdit(self.right_side)
        self.line_humi.setObjectName("line_humi")
        self.humi_edit.addWidget(self.line_humi)
        self.btn_humi = QtWidgets.QPushButton(self.right_side)
        self.btn_humi.setObjectName("btn_humi")
        self.humi_edit.addWidget(self.btn_humi)
        self.humi_edit.setStretch(0, 3)
        self.humi_edit.setStretch(1, 1)
        self.verticalLayout_3.addLayout(self.humi_edit)
        spacerItem1 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.threshold_table = QtWidgets.QTableWidget(self.right_side)
        self.threshold_table.setRowCount(3)
        self.threshold_table.setColumnCount(4)
        self.threshold_table.setObjectName("threshold_table")
        self.threshold_table.verticalHeader().setVisible(False)
        self.verticalLayout_3.addWidget(self.threshold_table)
        self.ship_incline = QtWidgets.QGroupBox(self.right_side)
        self.ship_incline.setObjectName("ship_incline")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.ship_incline)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.bar_chart = QtWidgets.QWidget(self.ship_incline)
        self.bar_chart.setObjectName("bar_chart")
        self.verticalLayout_4.addWidget(self.bar_chart)
        self.verticalLayout_3.addWidget(self.ship_incline)
        self.verticalLayout_3.setStretch(0, 2)
        self.verticalLayout_3.setStretch(2, 2)
        self.verticalLayout_3.setStretch(3, 2)
        self.verticalLayout_3.setStretch(5, 2)
        self.verticalLayout_3.setStretch(6, 3)
        self.horizontalLayout.addWidget(self.right_side)
        self.horizontalLayout.setStretch(0, 5)
        self.horizontalLayout.setStretch(1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 840, 25))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionShare = QtWidgets.QAction(MainWindow)
        self.actionShare.setObjectName("actionShare")
        self.actionAuto_Save = QtWidgets.QAction(MainWindow)
        self.actionAuto_Save.setObjectName("actionAuto_Save")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionExel = QtWidgets.QAction(MainWindow)
        self.actionExel.setObjectName("actionExel")
        self.actionShow_All_Commands = QtWidgets.QAction(MainWindow)
        self.actionShow_All_Commands.setObjectName("actionShow_All_Commands")
        self.actionDocumentation = QtWidgets.QAction(MainWindow)
        self.actionDocumentation.setObjectName("actionDocumentation")
        self.actionShow_Release_Notes = QtWidgets.QAction(MainWindow)
        self.actionShow_Release_Notes.setObjectName("actionShow_Release_Notes")
        self.actionView_License = QtWidgets.QAction(MainWindow)
        self.actionView_License.setObjectName("actionView_License")
        self.actionCheck_for_Updates = QtWidgets.QAction(MainWindow)
        self.actionCheck_for_Updates.setObjectName("actionCheck_for_Updates")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuFile.addAction(self.actionExel)
        self.menuFile.addAction(self.actionShare)
        self.menuFile.addAction(self.actionAuto_Save)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionShow_All_Commands)
        self.menuHelp.addAction(self.actionDocumentation)
        self.menuHelp.addAction(self.actionShow_Release_Notes)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionView_License)
        self.menuHelp.addAction(self.actionCheck_for_Updates)
        self.menuHelp.addSeparator()
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.sensor_group.setTitle(_translate("MainWindow", "SENSOR"))
        self.command_group.setTitle(_translate("MainWindow", "COMMAND"))
        self.btn_temp.setText(_translate("MainWindow", "Send"))
        self.btn_humi.setText(_translate("MainWindow", "Send"))
        self.ship_incline.setTitle(_translate("MainWindow", "SHIP_STATUS"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuView.setTitle(_translate("MainWindow", "View"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionShare.setText(_translate("MainWindow", "Share"))
        self.actionAuto_Save.setText(_translate("MainWindow", "Auto Save"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionExel.setText(_translate("MainWindow", "Exel"))
        self.actionShow_All_Commands.setText(_translate("MainWindow", "Show All Commands"))
        self.actionDocumentation.setText(_translate("MainWindow", "Documentation"))
        self.actionShow_Release_Notes.setText(_translate("MainWindow", "Show Release Notes"))
        self.actionView_License.setText(_translate("MainWindow", "View License"))
        self.actionCheck_for_Updates.setText(_translate("MainWindow", "Check for Updates"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
